# Generated by Django 4.2.14 on 2024-08-08 08:40

from django.db import migrations, models
import django.db.models.deletion
import myapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "Stu_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("Student_name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact", models.CharField(max_length=15)),
                ("address", models.TextField()),
                ("DOB", models.DateField()),
                ("joining_date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "profile_picture",
                    models.ImageField(upload_to=myapp.models.user_directory_path),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "Teach_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contact", models.CharField(max_length=15)),
                (
                    "students",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teachers",
                        to="myapp.student",
                    ),
                ),
                (
                    "subjects",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_staff",
                        to="myapp.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="enrolled_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrolled_students",
                to="myapp.subject",
            ),
        ),
    ]
