# Generated by Django 4.2.14 on 2024-08-08 11:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="student", old_name="DOB", new_name="dob",),
        migrations.RenameField(
            model_name="student", old_name="Student_name", new_name="student_name",
        ),
        migrations.RemoveField(model_name="student", name="Stu_id",),
        migrations.RemoveField(model_name="teacher", name="Teach_id",),
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(model_name="student", name="enrolled_subject",),
        migrations.AlterField(
            model_name="subject",
            name="code",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.RemoveField(model_name="teacher", name="students",),
        migrations.AddField(
            model_name="student",
            name="stu_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="teach_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="enrolled_subject",
            field=models.ManyToManyField(
                related_name="enrolled_students", to="myapp.subject"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="students",
            field=models.ManyToManyField(related_name="teachers", to="myapp.student"),
        ),
    ]
